# Generated by Django 5.2.5 on 2025-09-07 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description_html", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("departmental", "Departmental"),
                            ("non_departmental", "Non-Departmental"),
                            ("outside", "Outside the university"),
                        ],
                        max_length=32,
                    ),
                ),
                ("venue", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("registration_open", models.BooleanField(default=False)),
                ("featured", models.BooleanField(default=False)),
                ("online_link", models.URLField(blank=True)),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/covers/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
                "indexes": [
                    models.Index(
                        fields=["start_time", "status"],
                        name="events_even_start_t_ade85e_idx",
                    ),
                    models.Index(
                        fields=["featured"], name="events_even_feature_e0a35e_idx"
                    ),
                    models.Index(
                        fields=["category"], name="events_even_categor_aca11d_idx"
                    ),
                ],
            },
        ),
    ]
